dev:
  phpbb:
    param:
      classname: DebugPDO
test:
  phpbb:
    param:
      classname: DebugPDO
all:
  phpbb:
    class: sfDoctrineDatabase
    param:
      encoding: utf8
      dsn: 'mysql:host=localhost;dbname=yourDbName'
      username: yourUserName
      password: yourPassword
